### ISSUE TITLE
multiple words support

### ISSUE THREAD

**Issue by blshkv** [localh0t/m4ngl3m3#1]
Hi, thank you for providing a tool with good potentials.

I'm trying to generate a password list for wifi access point which has 3 words in the SSID name.
The chance is high that the password contains one or all three words with or without spaces, upper case , extra characters and so on.

Please add a feature which would allow to generate a wordlist based on this scenario.

Thank you.

**Comment by localh0t** [comment]
Hi @blshkv, thanks for the recommendation. I think that the problem you are facing is generating the correct input list of strings first, and that is something the tool should not be doing.
Here you have a quick n' dirty Python code that will do exactly what you want:

```python
#!/usr/bin/env python2.7

# Generate all possible permutations with given strings list

import itertools
import sys

with open(sys.argv[1]) as file_words_permutate:
    words_permutate = file_words_permutate.read().splitlines()

    for how_many in xrange(1, len(words_permutate) + 1):
        this_list = list(itertools.permutations(words_permutate, how_many))

        for permutation in this_list:
            print ' '.join(list(permutation))
sys.exit(0)

```

Example output:

```
$ cat input.txt
word1
word2
word3
$ python permutate.py input.txt
word1
word2
word3
word1 word2
word1 word3
word2 word1
word2 word3
word3 word1
word3 word2
word1 word2 word3
word1 word3 word2
word2 word1 word3
word2 word3 word1
word3 word1 word2
word3 word2 word1
```
After generating this list, you can simply save it to a text file and pass it to **m4ngl3m3!**. If you want, you can change the separator used, in line **#15** (in this example is a blank space).
I might add this as an auxiliary utility in the (near) future.

Thank you!

**Comment by blshkv** [comment]
I dont think this is what I wanted. The final output (dictionary) should look like following:
```
word1
word1word2
word1word2word3
Word1
Word1word2
Word1word2word3
Word1Word2
Word1Word2Word3
WORD1WORD2
WORD1WORD2WORD3
Word1word2word3
Word1Word2Word3
WORD1WORD2WORD3
..
<prefix>word1<suffix>
<prefix>word1word2<suffix>
```

and may be even this:
```
word1<symbol>word2<symbol>word3<symbol>
```
and so on
