### ISSUE TITLE
Letter case changing

### ISSUE THREAD

**Issue by fusion2222** [localh0t/m4ngl3m3#3]
Currently words are used only in their simplest form OR are capitalized. For example having word `Companyname` would result into following:

```
Companyname
COMPANYNAME
```

Which is cool.. however letter case permutation would be cool feature too:

```
Companyname
cOmpanyname
coMpanyname
...
```

**Comment by localh0t** [comment]
This feature was added in v0.1.2 ("RecursiveCase" mutation method). Thank you for your feedback.
